# Using the node alpine image to build the React app
image: node:10.15.2

# Cache modules between all pipelines in project
cache:
  key: ${CI_PROJECT_NAME}
  paths:
  - .yarn-cache

before_script:
  - yarn install --cache-folder .yarn-cache

stages:
  - test
  - build
  - semantic-release
  - publish

# JOBS

Test:
  stage: test
  except:
    - tags
  script:
    - yarn lint
    - yarn test:coverage

Build:
  stage: build
  except:
    - tags
  script:
    - yarn build:lib

Semantic Release:
  stage: semantic-release
  when: manual
  allow_failure: false
  only:
    - master
  script:
    - yarn semantic-release

Publish on NPM:
  stage: publish
  only:
    - tags
  script:
    - yarn build:lib
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm config set unsafe-perm true
    - npm publish --access public
