# Using the node alpine image to build the React app
image: node:10.15.2

stages:
  - install
  - test
  - build
  - semantic-release
  - publish

# JOBS
Install:
  stage: install
  script:
    - yarn
  except:
    - tags
  artifacts:
    paths:
      - node_modules/
    expire_in: 10 minutes

Test:
  stage: test
  except:
    - tags
  script:
    - yarn lint
    - yarn test:coverage

Build:
  stage: build
  except:
    - tags
  script:
    - yarn build:lib
  artifacts:
    paths:
      - dist
    expire_in: 10 minutes

Semantic-Release:
  stage: semantic-release
  only:
    - master
  script:
    - yarn semantic-release

Publish-On-NPM:
  stage: publish
  only:
    - tags
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm config set unsafe-perm true
    - npm publish --access public
