# Using the node alpine image to build the React app
image: node:10.15.2

# Cache modules between all pipelines in project
cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .yarn-cache

stages:
  - install
  - test
  - build
  - semantic-release
  - publish

# JOBS

Install:
  stage: install
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/
    expire_in: 10 minutes

Test:
  stage: test
  except:
    - tags
  script:
    - yarn lint
    - yarn test:coverage

Build:
  stage: build
  except:
    - tags
  script:
    - yarn build:lib

Semantic Release:
  stage: semantic-release
  when: manual
  allow_failure: false
  only:
    - master
  script:
    - yarn semantic-release

Publish on NPM:
  stage: publish
  only:
    - tags
  script:
    - yarn build:lib
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm config set unsafe-perm true
    - npm publish --access public
